const types = {
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",

  SET_SORT_GOODS: "SET_SORT_GOODS",
  SET_GOODS_LIST: "SET_GOODS_LIST",
  SET_ORDERS: "SET_ORDERS",
  SET_OPENED_MODAL: "SET_OPENED_MODAL",
  SET_PROFILE: "SET_PROFILE",
  SET_IS_ADMIN: "SET_IS_ADMIN",
  SET_IS_AUTH: "SET_IS_AUTH",

  SET_MENU_CATEGORY: "SET_MENU_CATEGORY",
  SET_FILTERS: "SET_FILTERS"
};

export default types;
